/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.base.Splitter;

@SuppressWarnings("java:S106")
public class HelloOtus {
    public static void main(String... args) {
        Splitter.on(',').trimResults().omitEmptyStrings().split("abc, bcd,, cde   ,zsa");
    }
}
